/**
 * Configuration for Aktionswert-Einheit (AVE) calculations.
 * Defines the relative values of resources, effects, and balancing parameters
 * for evaluating the economic viability of properties, facilities, and actions.
 */

// Values for different types of resources in AVE
export interface AveResourceValues {
  gold: number; // AVE per 1 unit of Gold

  // Per-round resource values
  laborPowerPerRound: number; // AVE per 1 unit of permanent Labor Power generated per round
  temporaryInfluencePerRound: number; // AVE per 1 unit of temporary Influence generated per round
  permanentInfluencePerRound: number; // AVE per 1 unit of permanent Influence generated per round

  // One-time resource cost/gain values
  laborPowerOneTime: number; // AVE per 1 unit of Labor Power spent/gained as a one-time amount
  temporaryInfluenceOneTime: number; // AVE per 1 unit of Temporary Influence spent/gained as a one-time amount

  // Default AVE for raw materials if not specified individually
  // Based on 1 RM (Durchschnittswert) ≈ 0.02 AVE from AVE.MD
  defaultRawMaterial: number;
  // Default AVE for special materials if not specified individually
  // Based on 1 SM (Durchschnittswert, da 1 SM = 2 Gold, 1 Gold = 0.1 AVE) ≈ 0.2 AVE from AVE.MD
  defaultSpecialMaterial: number;

  // Specific AVEs per unit for individual material types (can override default)
  rawMaterials: Record<string, number>; // e.g., { wood: 0.02, iron: 0.05 }
  specialMaterials: Record<string, number>; // e.g., { tools: 0.2, weapons: 0.5 }
}

// Values for different types of effects in AVE
export interface AveEffectValues {
  dcReductionPoint: number; // AVE per 1 point of DC reduction for an action
  combatPowerPoint: number; // AVE per 1 point of combat power
  // Example: AVE per unit of storage capacity (proxy for value of preventing decay)
  // storageUnitRaw?: number;
  // storageUnitSpecial?: number;
  // Example: AVE generated by one subject/tenant per round
  // perSubjectPerRound?: number;
}

// Balancing parameters for AVE calculations
export interface AveBalancingParameters {
  // The number of rounds over which the benefits of a property/facility are summed up
  // to compare against its acquisition cost.
  paybackPeriodRounds: number;
  // A multiplier indicating the desired return on investment.
  // E.g., 1.1 means the discounted benefits should be 110% of the acquisition cost.
  targetInvestmentReturnRatio: number;
  // Optional: A discount rate per round for future benefits, if a more complex model is needed.
  // discountRatePerRound?: number;
}

// Main AVE configuration structure
export interface AveConfig {
  resources: AveResourceValues;
  effects: AveEffectValues;
  balancing: AveBalancingParameters;
}

/**
 * Represents the calculated AVE (Aktionswert-Einheit) profile for a game entity (e.g., Property, Facility).
 * This helps in balancing and understanding the economic value of game elements.
 */
export interface AveProfile {
  acquisitionCostAVE: number; // Total AVE of acquiring the entity.
  maintenanceCostPerRoundAVE: number; // Total AVE of maintaining the entity per round.
  benefitsPerRoundAVE: number; // Total AVE of benefits generated by the entity per round.
  netBenefitPerRoundAVE: number; // (Benefits per round AVE) - (Maintenance per round AVE).
  totalNetBenefitOverPaybackPeriodAVE: number; // Net benefit per round AVE * paybackPeriodRounds.
  paybackFactor: number; // (Total net benefit over payback period AVE) / (Acquisition cost AVE).
  // Indicates return on investment; ideally around targetInvestmentReturnRatio.
}

// Default configuration values, inspired by docs/AVE.MD and initial estimates.
// These values will require significant tuning and playtesting.
export const DEFAULT_AVE_CONFIG: AveConfig = {
  resources: {
    gold: 0.1, // 1 Gold ≈ 0.1 AVE

    laborPowerPerRound: 0.8, // 1 AK (permanent pro Runde) ≈ 0.8 AVE
    temporaryInfluencePerRound: 0.2, // 1 Semipermanenter Einfluss (pro Runde) ≈ 0.2 AVE (assuming this is temp influence generated each round)
    permanentInfluencePerRound: 0.5, // 1 Permanent anfallender Einfluss (pro Runde) ≈ 0.5 AVE

    laborPowerOneTime: 0.15, // 1 AK (temporär für die Aktion) ≈ 0.15 AVE
    temporaryInfluenceOneTime: 0.05, // 1 Temporärer Einfluss ≈ 0.05 AVE

    defaultRawMaterial: 0.02, // 1 RM (Durchschnittswert) ≈ 0.02 AVE
    defaultSpecialMaterial: 0.2, // 1 SM (Durchschnittswert, 1SM=2G, 1G=0.1AVE) ≈ 0.2 AVE

    rawMaterials: {
      // Specific overrides can be added here if a material's value deviates
      // significantly from the default or its gold conversion value.
      // e.g., "magicOre": 0.1
    },
    specialMaterials: {
      // e.g., "magicMetals": 0.5
    },
  },
  effects: {
    dcReductionPoint: 0.075, // DC-Punkt (Senkung um 1) ≈ 0.05 - 0.1 AVE
    combatPowerPoint: 0.1, // Example: 1 CP = 0.1 AVE (needs balancing)
  },
  balancing: {
    paybackPeriodRounds: 15, // Standard period to evaluate return on investment
    targetInvestmentReturnRatio: 1.1, // Aim for benefits to be 110% of costs over payback period
  },
};
