import type {
  MaterialKind,
  MaterialTier,
  RawMarketGroup,
  SpecialMarketGroup,
} from '../domain/types';

export type MaterialTag =
  | 'food'
  | 'building'
  | 'consumable'
  | 'craft'
  | 'luxury'
  | 'military'
  | 'weapon'
  | 'armor'
  | 'metal'
  | 'animal'
  | 'magic'
  | 'medicine'
  | 'alchemy'
  | 'undead'
  | 'improved'
  | 'refined2';

export type MaterialDefinition = {
  id: string;
  label: string;
  kind: MaterialKind;
  tier: MaterialTier;
  marketGroup: RawMarketGroup | SpecialMarketGroup;
  saleBonusGold: number;
  tags: MaterialTag[];
};

function m(def: MaterialDefinition): MaterialDefinition {
  return def;
}

// Material catalog extracted from the "Marktsystem" section in Aufbausystem.md.
// IDs are stable internal keys; labels are German for UI/logging.
export const MATERIALS_V1: Readonly<Record<string, MaterialDefinition>> = {
  // Rohmaterial (billig)
  'raw.clay': m({
    id: 'raw.clay',
    label: 'Ton',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 0,
    tags: ['building'],
  }),
  'raw.quartzSand': m({
    id: 'raw.quartzSand',
    label: 'Quarzsand',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 0,
    tags: ['building'],
  }),
  'raw.tar': m({
    id: 'raw.tar',
    label: 'Teer',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 0,
    tags: ['building', 'military'],
  }),
  'raw.wood': m({
    id: 'raw.wood',
    label: 'Holz',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 0,
    tags: ['building', 'military'],
  }),
  'raw.wool': m({
    id: 'raw.wool',
    label: 'Wolle',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapConsumable',
    saleBonusGold: 0,
    tags: ['consumable'],
  }),
  'raw.fruit': m({
    id: 'raw.fruit',
    label: 'Obst',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 0,
    tags: ['food', 'consumable'],
  }),
  'raw.grapes': m({
    id: 'raw.grapes',
    label: 'Weinreben/Trauben',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 0,
    tags: ['food', 'consumable'],
  }),
  'raw.grain': m({
    id: 'raw.grain',
    label: 'Getreide',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 0,
    tags: ['food', 'military'],
  }),
  'raw.vegetables': m({
    id: 'raw.vegetables',
    label: 'Gemüse',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 0,
    tags: ['food'],
  }),
  'raw.herbsFlowers': m({
    id: 'raw.herbsFlowers',
    label: 'Kräuter/Blumen',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapConsumable',
    saleBonusGold: 0,
    tags: ['consumable', 'medicine'],
  }),
  'raw.olives': m({
    id: 'raw.olives',
    label: 'Oliven',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 0,
    tags: ['food'],
  }),
  'raw.stone': m({
    id: 'raw.stone',
    label: 'Stein',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 0,
    tags: ['building'],
  }),
  // Verbesserte RM (billig)
  'raw.pottery': m({
    id: 'raw.pottery',
    label: 'Tonware (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapConsumable',
    saleBonusGold: 1,
    tags: ['consumable', 'improved'],
  }),
  'raw.bread': m({
    id: 'raw.bread',
    label: 'Brot (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 1,
    tags: ['food', 'military', 'improved'],
  }),
  'raw.lumber': m({
    id: 'raw.lumber',
    label: 'Bauholz (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 1,
    tags: ['building', 'military', 'improved'],
  }),
  'raw.bricks': m({
    id: 'raw.bricks',
    label: 'Ziegel (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapBuilding',
    saleBonusGold: 1,
    tags: ['building', 'improved'],
  }),
  'raw.dairy': m({
    id: 'raw.dairy',
    label: 'Milch/Käse (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 1,
    tags: ['food', 'improved'],
  }),
  'raw.charcoal': m({
    id: 'raw.charcoal',
    label: 'Holzkohle (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapConsumable',
    saleBonusGold: 1,
    tags: ['consumable', 'improved'],
  }),
  'raw.fishPreserved': m({
    id: 'raw.fishPreserved',
    label: 'Fisch/Pökelfisch (verbessert)',
    kind: 'raw',
    tier: 'cheap',
    marketGroup: 'rawCheapFood',
    saleBonusGold: 1,
    tags: ['food', 'military', 'improved'],
  }),

  // Rohmaterial (einfach)
  'raw.buildStone': m({
    id: 'raw.buildStone',
    label: 'Baugestein',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicBuilding',
    saleBonusGold: 0,
    tags: ['building'],
  }),
  'raw.honey': m({
    id: 'raw.honey',
    label: 'Honig',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 0,
    tags: ['consumable', 'food'],
  }),
  'raw.ironOre': m({
    id: 'raw.ironOre',
    label: 'Eisenerz',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 0,
    tags: ['metal', 'building', 'military'],
  }),
  'raw.leather': m({
    id: 'raw.leather',
    label: 'Leder',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 0,
    tags: ['consumable', 'military'],
  }),
  'raw.copperOre': m({
    id: 'raw.copperOre',
    label: 'Kupfererz',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 0,
    tags: ['metal', 'building'],
  }),
  'raw.leadBrassTin': m({
    id: 'raw.leadBrassTin',
    label: 'Blei/Messing/Zinn',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 1,
    tags: ['metal', 'building'],
  }),
  'raw.salt': m({
    id: 'raw.salt',
    label: 'Salz',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 1,
    tags: ['food', 'military', 'consumable'],
  }),
  'raw.pigsSheepVarken': m({
    id: 'raw.pigsSheepVarken',
    label: 'Schweine/Schafe/Varken',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicFood',
    saleBonusGold: 2,
    tags: ['animal', 'food', 'military'],
  }),
  // Verbesserte RM (einfach)
  'raw.aquavit': m({
    id: 'raw.aquavit',
    label: 'Aquavit (verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 1,
    tags: ['food', 'consumable', 'improved'],
  }),
  'raw.leatherGoods': m({
    id: 'raw.leatherGoods',
    label: 'Lederwaren (verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 1,
    tags: ['consumable', 'military', 'improved'],
  }),
  'raw.bronze': m({
    id: 'raw.bronze',
    label: 'Bronze (verhüttet; verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 1,
    tags: ['metal', 'building', 'improved'],
  }),
  'raw.iron': m({
    id: 'raw.iron',
    label: 'Eisen (verhüttet; verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 1,
    tags: ['metal', 'building', 'military', 'improved'],
  }),
  'raw.meatPreserved': m({
    id: 'raw.meatPreserved',
    label: 'Fleisch/Pökelfleisch (verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicFood',
    saleBonusGold: 2,
    tags: ['food', 'military', 'improved'],
  }),
  'raw.steel': m({
    id: 'raw.steel',
    label: 'Stahl (verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 2,
    tags: ['metal', 'building', 'military', 'improved'],
  }),
  'raw.oliveOil': m({
    id: 'raw.oliveOil',
    label: 'Olivenöl (verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 2,
    tags: ['consumable', 'military', 'improved'],
  }),
  'raw.wine': m({
    id: 'raw.wine',
    label: 'Wein (verbessert)',
    kind: 'raw',
    tier: 'basic',
    marketGroup: 'rawBasicConsumable',
    saleBonusGold: 3,
    tags: ['luxury', 'consumable', 'improved'],
  }),

  // Rohmaterial (teuer)
  'raw.marbleGranite': m({
    id: 'raw.marbleGranite',
    label: 'Granit/Marmor',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveBuilding',
    saleBonusGold: 0,
    tags: ['building'],
  }),
  'raw.hardwood': m({
    id: 'raw.hardwood',
    label: 'Edelhölzer',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveBuilding',
    saleBonusGold: 0,
    tags: ['building'],
  }),
  'raw.wildGame': m({
    id: 'raw.wildGame',
    label: 'Wildbret',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 1,
    tags: ['food', 'luxury'],
  }),
  'raw.unpolishedGems': m({
    id: 'raw.unpolishedGems',
    label: 'Ungeschliffene Kristalle/Edelsteine',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 2,
    tags: ['luxury', 'magic'],
  }),
  'raw.optrolith': m({
    id: 'raw.optrolith',
    label: 'Optrolith',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveBuilding',
    saleBonusGold: 2,
    tags: ['building', 'magic'],
  }),
  'raw.packAnimals': m({
    id: 'raw.packAnimals',
    label: 'Lasttiere',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 4,
    tags: ['animal', 'building', 'military'],
  }),
  'raw.furs': m({
    id: 'raw.furs',
    label: 'Pelze',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 4,
    tags: ['luxury', 'consumable'],
  }),
  'raw.magicPlants': m({
    id: 'raw.magicPlants',
    label: 'Magische Pflanzen/Gewächse',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 4,
    tags: ['luxury', 'magic'],
  }),
  'raw.lesserMagicOres': m({
    id: 'raw.lesserMagicOres',
    label: 'Mindere magische Erze',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 6,
    tags: ['luxury', 'magic'],
  }),
  'raw.cattle': m({
    id: 'raw.cattle',
    label: 'Rinder',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 6,
    tags: ['animal', 'food', 'military'],
  }),
  'raw.exoticBeasts': m({
    id: 'raw.exoticBeasts',
    label: 'Exotische Biester',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 8,
    tags: ['animal', 'luxury'],
  }),
  'raw.preciousMetals': m({
    id: 'raw.preciousMetals',
    label: 'Edelmetalle',
    kind: 'raw',
    tier: 'expensive',
    marketGroup: 'rawExpensiveOther',
    saleBonusGold: 8,
    tags: ['metal', 'luxury'],
  }),

  // Sondermaterial (billig)
  'special.pulpellen': m({
    id: 'special.pulpellen',
    label: 'Pulpellen',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapFood',
    saleBonusGold: -1,
    tags: ['food', 'consumable', 'military'],
  }),
  'special.soap': m({
    id: 'special.soap',
    label: 'Seife',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapConsumable',
    saleBonusGold: -1,
    tags: ['consumable'],
  }),
  'special.simpleTools': m({
    id: 'special.simpleTools',
    label: 'Einfache Werkzeuge',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapCraft',
    saleBonusGold: 0,
    tags: ['craft', 'building', 'military'],
  }),
  'special.brandy': m({
    id: 'special.brandy',
    label: 'Brandt',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapFood',
    saleBonusGold: 0,
    tags: ['consumable', 'food'],
  }),
  'special.honeyMead': m({
    id: 'special.honeyMead',
    label: 'Honigmet',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapFood',
    saleBonusGold: 0,
    tags: ['consumable', 'food'],
  }),
  'special.candles': m({
    id: 'special.candles',
    label: 'Kerzen',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapConsumable',
    saleBonusGold: 0,
    tags: ['consumable'],
  }),
  'special.paper': m({
    id: 'special.paper',
    label: 'Papier',
    kind: 'special',
    tier: 'cheap',
    marketGroup: 'specialCheapOther',
    saleBonusGold: 0,
    tags: ['consumable'],
  }),

  // Sondermaterial (einfach)
  'special.bronzeGoods': m({
    id: 'special.bronzeGoods',
    label: 'Bronzeware',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicCraft',
    saleBonusGold: 0,
    tags: ['craft', 'metal', 'consumable'],
  }),
  'special.furniture': m({
    id: 'special.furniture',
    label: 'Möbel',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicCraft',
    saleBonusGold: 0,
    tags: ['consumable', 'building'],
  }),
  'special.cloth': m({
    id: 'special.cloth',
    label: 'Tuche',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicCraft',
    saleBonusGold: 1,
    tags: ['consumable'],
  }),
  'special.dyes': m({
    id: 'special.dyes',
    label: 'Farbstoffe/Tinkturen/Lacke',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicOther',
    saleBonusGold: 1,
    tags: ['consumable', 'alchemy', 'medicine'],
  }),
  'special.weaponsShields': m({
    id: 'special.weaponsShields',
    label: 'Waffen & Schilde',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicCraft',
    saleBonusGold: 1,
    tags: ['military', 'weapon'],
  }),
  'special.fineWine': m({
    id: 'special.fineWine',
    label: 'Edler Wein',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicOther',
    saleBonusGold: 1,
    tags: ['luxury', 'consumable'],
  }),
  'special.glassware': m({
    id: 'special.glassware',
    label: 'Glaswaren',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicCraft',
    saleBonusGold: 2,
    tags: ['luxury', 'building'],
  }),
  'special.optrolithCut': m({
    id: 'special.optrolithCut',
    label: 'Geschliffener Optrolith',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicBuilding',
    saleBonusGold: 2,
    tags: ['luxury', 'building', 'magic'],
  }),
  'special.armor': m({
    id: 'special.armor',
    label: 'Rüstungen',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicCraft',
    saleBonusGold: 2,
    tags: ['military', 'armor'],
  }),
  'special.statuesMosaics': m({
    id: 'special.statuesMosaics',
    label: 'Statuen/Kunstmosaike',
    kind: 'special',
    tier: 'basic',
    marketGroup: 'specialBasicBuilding',
    saleBonusGold: 2,
    tags: ['luxury', 'building'],
  }),

  // Sondermaterial (teuer / refined)
  'special.booksMaps': m({
    id: 'special.booksMaps',
    label: 'Bücher/Kartenmaterial',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 1,
    tags: ['luxury'],
  }),
  'special.spices': m({
    id: 'special.spices',
    label: 'Gewürze',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 1,
    tags: ['luxury', 'consumable'],
  }),
  'special.expensiveFurniture': m({
    id: 'special.expensiveFurniture',
    label: 'Teure Möbel',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 1,
    tags: ['luxury', 'consumable'],
  }),
  'special.specialTools': m({
    id: 'special.specialTools',
    label: 'Spezialwerkzeuge (Sonderwerkzeug)',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveCraft',
    saleBonusGold: 1,
    tags: ['craft', 'military'],
  }),
  'special.sacredOils': m({
    id: 'special.sacredOils',
    label: 'Heilige Öle/Weihrauch',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 1,
    tags: ['luxury', 'consumable'],
  }),
  'special.fineCloth': m({
    id: 'special.fineCloth',
    label: 'Teure Tuche',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveCraft',
    saleBonusGold: 1,
    tags: ['luxury', 'consumable'],
  }),
  'special.magicParaphernalia': m({
    id: 'special.magicParaphernalia',
    label: 'Magische Paraphernalia',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 2,
    tags: ['magic', 'craft', 'luxury'],
  }),
  'special.horses': m({
    id: 'special.horses',
    label: 'Pferde/Monokeroi',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 2,
    tags: ['animal', 'military', 'luxury'],
  }),
  'special.cutGems': m({
    id: 'special.cutGems',
    label: 'Geschliffene Edelsteine/Kristall',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 2,
    tags: ['luxury', 'magic', 'refined2'],
  }),
  'special.mechanicalParts': m({
    id: 'special.mechanicalParts',
    label: 'Mechanische Teile',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveCraft',
    saleBonusGold: 2,
    tags: ['craft', 'luxury', 'refined2'],
  }),
  'special.undeadLabor': m({
    id: 'special.undeadLabor',
    label: 'Untote Arbeitskräfte',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 2,
    tags: ['magic', 'undead', 'refined2'],
  }),
  'special.magomechanicalParts': m({
    id: 'special.magomechanicalParts',
    label: 'Magomechanische Teile',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveCraft',
    saleBonusGold: 3,
    tags: ['craft', 'magic', 'luxury', 'refined2'],
  }),
  'special.potions': m({
    id: 'special.potions',
    label: 'Alchemische Tränke/Elixiere',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 3,
    tags: ['alchemy', 'medicine', 'luxury', 'refined2'],
  }),
  'special.perfume': m({
    id: 'special.perfume',
    label: 'Parfüms',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 3,
    tags: ['luxury', 'consumable', 'refined2'],
  }),
  'special.warhorses': m({
    id: 'special.warhorses',
    label: 'Schlachtrösser',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 3,
    tags: ['animal', 'military', 'refined2'],
  }),
  'special.smallChimeras': m({
    id: 'special.smallChimeras',
    label: 'Kleinchimären',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 3,
    tags: ['magic', 'animal', 'luxury', 'refined2'],
  }),
  'special.undeadCombat': m({
    id: 'special.undeadCombat',
    label: 'Untote Kämpfer',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 3,
    tags: ['magic', 'undead', 'military', 'refined2'],
  }),
  'special.minorMagicMetals': m({
    id: 'special.minorMagicMetals',
    label: 'Mindere magische Metalle/Legierungen',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 3,
    tags: ['magic', 'metal', 'luxury', 'refined2'],
  }),
  'special.jewelry': m({
    id: 'special.jewelry',
    label: 'Schmuck/Schmuckwerk',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveLuxury',
    saleBonusGold: 4,
    tags: ['luxury', 'refined2'],
  }),
  'special.highMagicOres': m({
    id: 'special.highMagicOres',
    label: 'Hochmagische Erze/Metalle',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 4,
    tags: ['luxury', 'magic', 'refined2'],
  }),
  'special.workChimeras': m({
    id: 'special.workChimeras',
    label: 'Arbeits‑Chimären/Golems',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 4,
    tags: ['magic', 'luxury', 'refined2'],
  }),
  'special.warChimeras': m({
    id: 'special.warChimeras',
    label: 'Kampfchimären/Konstrukte/Golems',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 4,
    tags: ['magic', 'military', 'luxury', 'refined2'],
  }),
  'special.minorMagicArtifacts': m({
    id: 'special.minorMagicArtifacts',
    label: 'Mindere magische Artefakte',
    kind: 'special',
    tier: 'expensive',
    marketGroup: 'specialExpensiveOther',
    saleBonusGold: 5,
    tags: ['magic', 'luxury', 'refined2'],
  }),
} as const;

export function getMaterialOrThrow(materialId: string): MaterialDefinition {
  const m = MATERIALS_V1[materialId];
  if (!m) throw new Error(`Unknown materialId: ${materialId}`);
  return m;
}

export function materialHasTag(materialId: string, tag: MaterialTag): boolean {
  return getMaterialOrThrow(materialId).tags.includes(tag);
}
